const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();const user='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
await db.exec(`create role anon; create role authenticated; create schema auth; create function auth.uid() returns uuid language sql stable as $$select current_setting('qa.uid')::uuid$$; grant usage on schema auth to authenticated; create table public.admin(id uuid primary key,demo_session_id uuid default auth.uid(),deleted_at timestamptz,delivery_batch_id text,bom_stock_issued_at timestamptz,delivery_status text,material_delivery_date text,driver_name text,driver_phone_number text,vehicle_number text,vendor text);`);
const base=await readFile(new URL('../../supabase-setup/01_solarflow_demo.sql',import.meta.url),'utf8');
let ddl=base.slice(base.indexOf('create table public.delivery_batches ('),base.indexOf('create table public.quotations (')).replace(' references auth.users(id) on delete cascade','');await db.exec(ddl);
const sql07=await readFile(new URL('../../supabase-setup/07_bom_delivery_stock.sql',import.meta.url),'utf8');
await db.exec(sql07.slice(sql07.indexOf('-- Save and disband are transactions too:'),sql07.lastIndexOf('commit;')));
await db.exec(`alter table admin enable row level security; alter table delivery_batches enable row level security; create policy own on admin to authenticated using(demo_session_id=auth.uid()) with check(demo_session_id=auth.uid()); create policy own on delivery_batches to authenticated using(demo_session_id=auth.uid()) with check(demo_session_id=auth.uid()); grant select,insert,update,delete on admin,delivery_batches to authenticated; set role authenticated; set qa.uid='${user}';`);
const p1='33333333-3333-4333-8333-333333333333',p2='44444444-4444-4444-8444-444444444444';
await db.query('insert into admin(id) values ($1),($2)',[p1,p2]);
const batch={id:'55555555-5555-4555-8555-555555555555',batch_no:'QA-1',status:'IN_TRANSIT'};
const save=(b,selected,removed=[])=>db.query('select save_delivery_batch_atomic($1::jsonb,$2::uuid[],$3::uuid[])',[JSON.stringify(b),selected,removed]);
const del=ids=>db.query('select delete_delivery_batch_atomic($1,$2::uuid[])',[batch.id,ids]);
await save(batch,[p1,p2]);assert.equal((await db.query("select count(*)::int n from admin where delivery_batch_id='QA-1'")).rows[0].n,2);
await assert.rejects(save(batch,[p1],[]),/changed/);assert.equal((await db.query('select cardinality(project_ids) n from delivery_batches')).rows[0].n,2);
await save(batch,[p1],[p2]);assert.equal((await db.query('select delivery_batch_id from admin where id=$1',[p2])).rows[0].delivery_batch_id,null);
await assert.rejects(save({...batch,id:'66666666-6666-4666-8666-666666666666',batch_no:'QA-2'},[p1]),/assigned elsewhere/);
await assert.rejects(del([p2]),/changed/);
await db.exec(`set qa.uid='${other}'`);await assert.rejects(del([p1]),/unavailable/);await db.exec(`set qa.uid='${user}'`);
await del([p1]);assert.equal((await db.query('select count(*)::int n from delivery_batches')).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from admin')).rows[0].n,2);
await assert.rejects(save(batch,[p1,'77777777-7777-4777-8777-777777777777']),/unavailable/);assert.equal((await db.query('select count(*)::int n from delivery_batches')).rows[0].n,0);
await save(batch,[p1]);await db.query("update delivery_batches set status='DELIVERED'");await assert.rejects(del([p1]),/Delivered/);await assert.rejects(save(batch,[p1]),/Delivered/);
console.log('PASS: create/link, edit/unlink, stale save/delete rollback, other-batch rejection, cross-visitor denial, disband preserves projects, missing project rollback, delivered batch protection');await db.close();
