import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || '/Users/mahvishsadafv2/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const output='output/quotation-qa';await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,channel:"chrome"});
try {
    const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});
    // No live API, external font, image or other network requests are permitted in this test.
    await context.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1' ? route.continue() : route.abort());
    const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto('http://127.0.0.1:5186/quotation-preview.html');
    await page.getByRole('heading',{name:'Test Customer A'}).waitFor();
    assert.equal(await page.locator('.q-header').count(),0);
    assert.equal(await page.locator('.q-hero').count(),0);
    assert.equal(await page.getByRole('button',{name:'Create Quotation',exact:true}).first().isVisible(),true);
    assert.equal(await page.getByRole('button',{name:'Add to Leads',exact:true}).first().isDisabled(),true);
    assert.ok(await page.evaluate(()=>document.querySelector('.q-module').scrollWidth<=innerWidth));
    assert.ok(await page.locator('.q-module.q-module-embedded').count());
    await page.screenshot({path:`${output}/mobile-list.png`,fullPage:true});
    const downloadEvent=page.waitForEvent('download');
    await page.getByRole('button',{name:'Download',exact:true}).first().click();
    const downloaded=await downloadEvent;
    await downloaded.saveAs(`${output}/quotation.pdf`);
    await page.getByText('Download complete',{exact:true}).waitFor();
    await page.getByRole('button',{name:'Understood',exact:true}).click();
    await page.getByRole('button',{name:'Issued',exact:true}).click();
    await page.locator('.q-status-issued',{hasText:'issued'}).waitFor();
    await page.getByRole('button',{name:'All',exact:true}).click();
    await page.getByRole('button',{name:'Create Quotation',exact:true}).first().click();
    assert.equal(await page.getByLabel('Salesperson name (automatic)',{exact:true}).inputValue(),'Test Agent');
    assert.equal(await page.getByLabel('Salesperson name (automatic)',{exact:true}).isEditable(),false);
    await page.getByLabel('Customer name',{exact:true}).fill('Local Mobile Test');
    await page.getByLabel('Phone number',{exact:true}).fill('0000000002');
    await page.getByText('Saved',{exact:true}).waitFor();
    const route=page.url();
    assert.ok(await page.evaluate(()=>document.querySelector('.q-module').scrollWidth<=innerWidth));
    await page.reload();await page.getByLabel('Customer name',{exact:true}).waitFor();
    assert.equal(await page.getByLabel('Customer name',{exact:true}).inputValue(),'Local Mobile Test');
    await page.evaluate(()=>window.quotationFixture.client.state.offline=true);
    await page.getByLabel('Full address',{exact:true}).fill('Recovered local address');
    await page.waitForTimeout(1200);
    assert.ok(await page.evaluate(()=>Object.keys(localStorage).some(k=>k.startsWith('solarflow:quotation:'))));
    await page.evaluate(()=>window.quotationFixture.client.state.offline=false);
    await page.getByRole('button',{name:'Save draft',exact:true}).click();
    await page.getByText('Saved',{exact:true}).waitFor();
    await page.getByRole('button',{name:'Back to quotations',exact:true}).click();
    await page.getByRole('button',{name:'Create Quotation',exact:true}).first().click();
    await page.getByRole('button',{name:'2 System'}).click();
    assert.equal(await page.getByLabel('Inverter option',{exact:true}).count(),0);
    assert.equal(await page.getByLabel('Inverter brand / make',{exact:true}).count(),1);
    await page.getByLabel('Module Wp',{exact:true}).fill('580');
    await page.getByLabel('No of Modules',{exact:true}).fill('6');
    await page.getByRole('button',{name:'Auto',exact:true}).click();
    assert.equal(await page.getByLabel('System Capacity (kWp)',{exact:true}).inputValue(),'3.48');
    await page.screenshot({path:`${output}/mobile-system.png`,fullPage:true});
    page.on('dialog',dialog=>dialog.accept());
    await page.goto('http://127.0.0.1:5186/quotation-preview.html#/quotations/22222222-2222-4222-8222-222222222222/preview');
    await page.locator('.a4-page').first().waitFor();
    await page.screenshot({path:`${output}/mobile-preview.png`,fullPage:true});
    await page.setViewportSize({width:1280,height:1000});
    await page.goto('http://127.0.0.1:5186/quotation-preview.html#/quotations/22222222-2222-4222-8222-222222222222/preview');
    await page.locator('.a4-page').first().waitFor();
    await page.screenshot({path:`${output}/desktop-preview.png`,fullPage:true});
    await page.setViewportSize({width:1440,height:900});
    await page.goto('http://127.0.0.1:5186/quotation-preview.html?role=admin#/quotations');
    await page.getByRole('heading',{name:'Test Customer A'}).waitFor();
    assert.equal(await page.locator('.q-header').count(),0);
    assert.equal(await page.locator('.q-hero').count(),0);
    await page.screenshot({path:`${output}/admin-desktop-list.png`,fullPage:true});
    await page.goto('http://127.0.0.1:5186/quotation-preview.html?role=agent2#/quotations');
    await page.getByRole('heading',{name:'Test Customer A'}).waitFor();
    assert.ok(await page.evaluate(()=>document.querySelector('.q-content').getBoundingClientRect().width<=448));
    assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('.q-cards')).gridTemplateColumns.split(' ').length),1);
    await page.screenshot({path:`${output}/dealer-desktop-compact.png`,fullPage:true});
    await page.setViewportSize({width:320,height:700});
    await page.goto('http://127.0.0.1:5186/quotation-preview.html?role=agent2#/quotations');
    await page.getByRole('heading',{name:'Test Customer A'}).waitFor();
    assert.equal(await page.getByRole('button',{name:'Add to Leads',exact:true}).first().isDisabled(),true);
    assert.ok(await page.evaluate(()=>document.querySelector('.q-module').scrollWidth<=innerWidth));
    await page.getByRole('button',{name:'Create Quotation',exact:true}).first().click();
    await page.getByLabel('Customer name',{exact:true}).waitFor();
    assert.ok(await page.evaluate(()=>document.querySelector('.q-module').scrollWidth<=innerWidth));
    await page.screenshot({path:`${output}/dealer-320-editor.png`,fullPage:true});
    for(const role of ['vendor','stamp']){await page.goto(`http://127.0.0.1:5186/quotation-preview.html?role=${role}#/quotations`);await page.getByText('Quotation Maker is unavailable for your role.',{exact:false}).waitFor();}
    assert.deepEqual(errors,[]);
    console.log(JSON.stringify({result:'pass',checks:['embedded quotation view without duplicate header or marketing hero','download changes draft to issued','mobile list','automatic read-only salesperson name','disabled Add to Leads action','mobile stepper','draft reopen','offline recovery','panel/inverter field separation','three-page PDF','desktop preview','admin desktop list','dealer access at 320px','mobile overflow guards','vendor and stamp UI guards'],draftRoute:route,output},null,2));
} finally {await browser.close();}
