// src/constants.js  -  SolarFlow Demo Energy
// Generated by SolarFlow Client Form · 6 August 2026 at 15:50
// CRN prefix: CRN-2026-

import {
    Users, ClipboardList, IndianRupee, Package, PauseCircle, Truck,
    Wrench, Camera, Send, Gauge, Zap, Activity, ClipboardCheck, CheckCircle2,
    Clock, AlertTriangle, Banknote, Tag, ShoppingBag
} from 'lucide-react';

export const PRIMARY_STAGES = [
    { id: 'LEADS', label: 'Leads', icon: Users },
    { id: 'REGISTRATION', label: 'Registration', icon: ClipboardList },
    { id: 'LOAN', label: 'Loan', icon: IndianRupee },
    { id: 'CASH', label: 'Cash', icon: Banknote },
    { id: 'MATERIAL ORDER', label: 'Material Order', icon: ShoppingBag },
    { id: 'MATERIAL INTEGRATION', label: 'Material Integration', icon: Package },
    { id: 'MATERIAL DELIVERY', label: 'Material Delivery', icon: Truck },
    { id: 'INSTALLATION STATUS', label: 'Installation Status', icon: Wrench },
    { id: 'GEO TAG PHOTO', label: 'Geo Tag Photo', icon: Camera },
    { id: 'DISCOM SUBMISSION', label: 'Discom Submission', icon: Send },
    { id: 'METER INSTALLATION', label: 'Meter Installation', icon: Gauge },
    { id: 'DISCOM INSPECTION', label: 'Discom Inspection', icon: ClipboardCheck },
    { id: 'SUBSIDY STATUS', label: 'Subsidy Status', icon: Tag },
    { id: 'FINAL REVIEW', label: 'Final Review', icon: ClipboardCheck },
    { id: 'COMPLETED', label: 'Completed', icon: CheckCircle2 },
    { id: 'LOST PROJECT', label: 'Lost Project', icon: PauseCircle },
];

export const STAGE_IDS = Object.fromEntries(
    PRIMARY_STAGES.map(s => [s.id.replace(/ /g, "_"), s.id])
);

// `isFinal: true` marks the terminal value for a tag - reaching it locks the
// record. Order here is the order shown in the UI.
export const SUBSIDY_TAGS = [
    { id: 'Inprocess', label: 'Inprocess', icon: Clock },
    { id: 'Redeemed', label: 'Redeemed', icon: Banknote },
    { id: 'Returned', label: 'Returned', icon: Clock },
    { id: 'Approved', label: 'Approved', icon: CheckCircle2 },
    { id: 'Received', label: 'Received', icon: CheckCircle2, isFinal: true },
];

export const SUBSIDY_TAG_COLORS = {
    'Received':   { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', dot: 'bg-emerald-400' },
    'Inprocess':  { bg: 'bg-teal-50',    text: 'text-teal-700',    border: 'border-teal-200',    dot: 'bg-teal-400' },
    'In Process': { bg: 'bg-teal-50',    text: 'text-teal-700',    border: 'border-teal-200',    dot: 'bg-teal-400' },
    'Redeemed':   { bg: 'bg-blue-50',    text: 'text-blue-700',    border: 'border-blue-200',    dot: 'bg-blue-400' },
    'Returned':   { bg: 'bg-amber-50',   text: 'text-amber-700',   border: 'border-amber-200',   dot: 'bg-amber-400' },
    'Approved':   { bg: 'bg-indigo-50',  text: 'text-indigo-700',  border: 'border-indigo-200',  dot: 'bg-indigo-400' },
    'Rejected':   { bg: 'bg-rose-50',    text: 'text-rose-700',    border: 'border-rose-200',    dot: 'bg-rose-400' },
};

export const LOAN_TAGS = [
    { id: 'Inprocess', label: 'Inprocess', icon: Clock },
    { id: 'Sanctioned', label: 'Sanctioned', icon: CheckCircle2 },
    { id: 'Returned', label: 'Returned', icon: Clock },
    { id: 'Reject', label: 'Reject', icon: AlertTriangle },
    { id: '1st Payment', label: '1st Payment', icon: Banknote },
    { id: '2nd Payment', label: '2nd Payment', icon: Banknote },
    { id: 'Total Loan Payment Received', label: 'Total Received', icon: CheckCircle2, isFinal: true },
];

export const LOAN_TAG_COLORS = {
    'Inprocess':                   { bg: 'bg-teal-50',    text: 'text-teal-700',    border: 'border-teal-200',    dot: 'bg-teal-400' },
    'Reject':                      { bg: 'bg-rose-50',    text: 'text-rose-700',    border: 'border-rose-200',    dot: 'bg-rose-400' },
    'Total Loan Payment Received': { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', dot: 'bg-emerald-400' },
    'Processed':   { bg: 'bg-indigo-50',  text: 'text-indigo-700',  border: 'border-indigo-200',  dot: 'bg-indigo-400' },
    'In Progress': { bg: 'bg-teal-50',    text: 'text-teal-700',    border: 'border-teal-200',    dot: 'bg-teal-400' },
    '1st Payment': { bg: 'bg-blue-50',    text: 'text-blue-700',    border: 'border-blue-200',    dot: 'bg-blue-400' },
    '2nd Payment': { bg: 'bg-purple-50',  text: 'text-purple-700',  border: 'border-purple-200',  dot: 'bg-purple-400' },
    'Sanctioned':  { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', dot: 'bg-emerald-400' },
    'Returned':    { bg: 'bg-amber-50',   text: 'text-amber-700',   border: 'border-amber-200',   dot: 'bg-amber-400' },
    'Rejected':    { bg: 'bg-rose-50',    text: 'text-rose-700',    border: 'border-rose-200',    dot: 'bg-rose-400' },
    'All Clear':   { bg: 'bg-emerald-50', text: 'text-emerald-800', border: 'border-emerald-200', dot: 'bg-emerald-500' },
};

// Supabase metadata table categories (one per managed dropdown)
export const META_CATEGORIES = ['payment_type', 'module_brand', 'payment_method_modes', 'subsidy_approval_status', 'registration_by'];

export const APP_ROLES = [
    { id: 'admin', label: 'Admin', user_type: 'admin', role: 'Admin' },
    { id: 'office', label: 'Office', user_type: 'sales', role: 'Office' },
    { id: 'channel_partner_office', label: 'Channel Partner Office', user_type: 'channel_partner_office', role: 'Channel Partner Office' },
    { id: 'office2', label: 'Manager', user_type: 'office2', role: 'Channel Partner Manager' },
    { id: 'agent2', label: 'Dealer', user_type: 'agent2', role: 'Channel Partner' },
    { id: 'channel_partner', label: 'Channel Partners', user_type: 'agent', role: 'Channel Partners' },
    { id: 'vendor', label: 'Vendors', user_type: 'vendor', role: 'Vendors' },
    { id: 'stamp', label: 'Stamp Guy', user_type: 'stamp', role: 'Stamp' },
];


// ============================================================
// ROOF BOM TEMPLATE (Exact Order)
// ============================================================

export const ROOF_BOM_TEMPLATE = [
    { sr_no: 1,  product_name: 'Solar Panel',             quantity: '',      uom: 'Nos', quantity_editable: true },
    { sr_no: 2,  product_name: 'Inverter',                quantity: '',      uom: 'Nos', quantity_editable: true },
    { sr_no: 3,  product_name: 'ACDB',                    quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 4,  product_name: 'DCDB',                    quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 5,  product_name: 'Dc Cable',                quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 6,  product_name: 'Earthing Cable',          quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 7,  product_name: '16sq MM LA cabel',        quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 8,  product_name: 'Ac Cable',                quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 9,  product_name: 'Isolation box+MCB',       quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 10, product_name: 'Shadel',                  quantity: '50',    uom: 'No.', quantity_editable: false },
    { sr_no: 11, product_name: 'Elbow',                   quantity: '35',    uom: 'No.', quantity_editable: false },
    { sr_no: 12, product_name: 'Tea',                     quantity: '7',     uom: 'No.', quantity_editable: false },
    { sr_no: 13, product_name: 'Wedge Anchor Fast',       quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 14, product_name: '8 aani 4 inch',           quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 15, product_name: '6 aani 6 inch',           quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 16, product_name: 'jasti khila',             quantity: '8',     uom: 'No.', quantity_editable: false },
    { sr_no: 17, product_name: 'm c 4 conectar',           quantity: '2',     uom: 'No.', quantity_editable: false },
    { sr_no: 18, product_name: 'Screw/ Tape',             quantity: '15',    uom: 'No.', quantity_editable: false },
    { sr_no: 19, product_name: '16 sq MM Round LUG',      quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 20, product_name: '4 sq MM Round LUG',       quantity: '3',     uom: 'No.', quantity_editable: false },
    { sr_no: 21, product_name: '4 Sqmm Pin Type Lug',     quantity: '10',    uom: 'No.', quantity_editable: false },
    { sr_no: 22, product_name: 'Red/Black Sleeve',        quantity: '5+2',   uom: 'No.', quantity_editable: false },
    { sr_no: 23, product_name: '5 aani 2inch',            quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 24, product_name: 'Mid Clamp',               quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 25, product_name: 'End Clamp',               quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 26, product_name: 'GI Clamp',                quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 27, product_name: 'u bolt+patti',            quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 28, product_name: 'Chaki+Wisher',            quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 29, product_name: 'Sapot pati',              quantity: '3',     uom: 'No.', quantity_editable: false },
    { sr_no: 30, product_name: 'rubar cap',               quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 31, product_name: 'cabale ties',             quantity: '15',    uom: 'No.', quantity_editable: false },
    { sr_no: 32, product_name: 'Cable Tie ( Nani )',      quantity: '36',    uom: 'No.', quantity_editable: false },
    { sr_no: 33, product_name: 'Earth Pit Doll',          quantity: '3',     uom: 'No.', quantity_editable: false },
    { sr_no: 34, product_name: '40*40 Pipe Perlin',       quantity: '',      uom: 'Feet', quantity_editable: true },
    { sr_no: 35, product_name: '60*40 Pipe rafter',       quantity: '',      uom: 'Feet', quantity_editable: true },
    { sr_no: 36, product_name: '60*40 front leg',         quantity: '',      uom: 'Feet', quantity_editable: true },
    { sr_no: 37, product_name: '60*40 Rear leg',          quantity: '',      uom: 'Feet', quantity_editable: true },
    { sr_no: 38, product_name: 'LA  insuletar',           quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 39, product_name: 'cabale tre',              quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 40, product_name: 'Earthing Kit + LA',       quantity: '3+1',   uom: 'No.', quantity_editable: false },
    { sr_no: 41, product_name: 'chemical',                quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 42, product_name: 'Conduite Pipe',           quantity: '15',    uom: 'No.', quantity_editable: false },
    { sr_no: 43, product_name: 'Cement',                  quantity: '',      uom: 'Bag', quantity_editable: true },
    { sr_no: 44, product_name: 'Reti',                    quantity: '',      uom: 'Bag (50 kg)', quantity_editable: true },
    { sr_no: 45, product_name: 'Kapachi',                 quantity: '',      uom: 'Bag (50 kg)', quantity_editable: true },
];


// ============================================================
// SHED BOM TEMPLATE (Exact Order)
// ============================================================

export const SHED_BOM_TEMPLATE = [
    { sr_no: 1,  product_name: 'Solar Panel',             quantity: '',      uom: 'Nos', quantity_editable: true },
    { sr_no: 2,  product_name: 'Inverter',                quantity: '',      uom: 'Nos', quantity_editable: true },
    { sr_no: 3,  product_name: 'ACDB',                    quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 4,  product_name: 'DCDB',                    quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 5,  product_name: 'Dc Cable',                quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 6,  product_name: 'Earthing Cable',          quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 7,  product_name: '16sq MM LA Cable',        quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 8,  product_name: 'Ac Cable',                quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 9,  product_name: 'Isolation box+MCB',       quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 10, product_name: 'Shadel',                  quantity: '50',    uom: 'No.', quantity_editable: false },
    { sr_no: 11, product_name: 'Elbow',                   quantity: '35',    uom: 'No.', quantity_editable: false },
    { sr_no: 12, product_name: 'Tea',                     quantity: '7',     uom: 'No.', quantity_editable: false },
    { sr_no: 13, product_name: 'Spring + HEX Bolt',       quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 14, product_name: 'L And Key',               quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 15, product_name: '80*40 J bolt mota',       quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 16, product_name: 'Damar roll',              quantity: '2',     uom: 'MTR', quantity_editable: false },
    { sr_no: 17, product_name: 'jasti khila',             quantity: '8',     uom: 'No.', quantity_editable: false },
    { sr_no: 18, product_name: 'm c 4 conectar',           quantity: '2',     uom: 'No.', quantity_editable: false },
    { sr_no: 19, product_name: '16 sq MM Round LUG',      quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 20, product_name: '4 sq MM Round LUG',       quantity: '3',     uom: 'No.', quantity_editable: false },
    { sr_no: 21, product_name: '4 Sqmm Pin Type Lug',     quantity: '10',    uom: 'No.', quantity_editable: false },
    { sr_no: 22, product_name: 'Red/Black Sleeve',        quantity: '5+2',   uom: 'No.', quantity_editable: false },
    { sr_no: 23, product_name: '5 aani 2inch',            quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 24, product_name: 'Mid Clamp',               quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 25, product_name: 'End Clamp',               quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 26, product_name: 'LA  insuletar',           quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 27, product_name: 'cabale ties',             quantity: '15',    uom: 'No.', quantity_editable: false },
    { sr_no: 28, product_name: 'Earthing ડોલ / ઢાંકણા', quantity: '3',     uom: 'No.', quantity_editable: false },
    { sr_no: 29, product_name: 'C Chanel',                quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 30, product_name: 'Z mota',                  quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 31, product_name: 'Z nana',                  quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 32, product_name: 'cabale tre',              quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 33, product_name: 'Earthing Kit + LA',       quantity: '3+1',   uom: 'No.', quantity_editable: false },
    { sr_no: 34, product_name: 'chemical',                quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 35, product_name: 'Condute Pipe',            quantity: '15',    uom: 'No.', quantity_editable: false },
];

export const COMMON_BOM_ITEMS = ROOF_BOM_TEMPLATE.filter(r => 
    SHED_BOM_TEMPLATE.some(s => s.product_name.toLowerCase().trim() === r.product_name.toLowerCase().trim())
);

// ════════════════════════════════════════════════════════════
// INSTALLATION STATUS TAGS
// ════════════════════════════════════════════════════════════
export const INSTALLATION_TAGS = [
    { id: 'Giveup', label: 'Giveup' },
    { id: 'In process', label: 'In process' },
    { id: 'Pending', label: 'Pending' },
    { id: 'Installed', label: 'Installed', isFinal: true }
];

export const INSTALLATION_TAG_COLORS = {
    'Giveup':     { bg: 'bg-rose-50',    text: 'text-rose-700',    border: 'border-rose-200',    dot: 'bg-rose-400' },
    'In process': { bg: 'bg-teal-50',    text: 'text-teal-700',    border: 'border-teal-200',    dot: 'bg-teal-400' },
    'Installed':  { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', dot: 'bg-emerald-400' },
    'Yes':     { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', dot: 'bg-emerald-500' },
    'Process': { bg: 'bg-teal-50',    text: 'text-teal-700',    border: 'border-teal-200',    dot: 'bg-teal-500' },
    'Pending': { bg: 'bg-amber-50',   text: 'text-amber-700',   border: 'border-amber-200',   dot: 'bg-amber-500' },
    'Give Up': { bg: 'bg-rose-50',    text: 'text-rose-700',    border: 'border-rose-200',    dot: 'bg-rose-500' }
};

// ════════════════════════════════════════════════════════════
// LOST PROJECT STATUS TAGS
// ════════════════════════════════════════════════════════════
export const HOLD_STATUS_TAGS = [
    { 
        id: 'Project Win', 
        label: 'Project Win', 
        activeClass: 'bg-emerald-600 text-white border-emerald-600 ring-2 ring-emerald-500 ring-offset-2 shadow-md shadow-emerald-600/25 font-bold scale-[1.02]', 
        dotClass: 'bg-white shadow-xs' 
    },
    { 
        id: 'Project Lost', 
        label: 'Project Lost', 
        activeClass: 'bg-rose-600 text-white border-rose-600 ring-2 ring-rose-500 ring-offset-2 shadow-md shadow-rose-600/25 font-bold scale-[1.02]', 
        dotClass: 'bg-white shadow-xs' 
    },
    { 
        id: 'Project Return Win', 
        label: 'Project Return Win', 
        activeClass: 'bg-amber-500 text-white border-amber-500 ring-2 ring-amber-400 ring-offset-2 shadow-md shadow-amber-500/25 font-bold scale-[1.02]', 
        dotClass: 'bg-white shadow-xs' 
    }
];

// ════════════════════════════════════════════════════════════
// DOCUMENT TYPE LABELS
// ════════════════════════════════════════════════════════════
export const DOC_TYPE_LABELS = {
    application_acknowledgment: 'Application Acknowledgment',
    vendor_feasibility: 'Vendor Feasibility',
    site_feasibility: 'Site Feasibility',
    adhaar_card_front: 'Aadhaar Card (Front)',
    adhaar_card_back: 'Aadhaar Card (Back)',
    pan_card: 'PAN Card',
    light_bill: 'Electricity / Light Bill',
    index_2: 'Index-2 / Name Match Copy',
    bank_details: 'Bank Passbook / Cheque',
    house_geo_tag_photo: 'House Photo with Geo Tag',
    extra_docs: 'Extra Documents',
    geo_tag_image: 'Site / Geo Tag Photo',
    sfdc_photo: 'SFDC Photo',
    file_status: 'File Status Doc',
    dcr_certificate: 'DCR Certificate',
    pcr_certificate: 'PCR Certificate',
    plant_commissioning_report: 'Plant Commissioning Report',
    signature_pic: 'Customer Signature',
    signature: 'Customer Signature',
    firstPartySignature: 'Customer Signature',
    customer_signature: 'Customer Signature',
    stamp: 'Vendor Stamp',
    stamp_pic: 'Vendor Stamp',
    vendor_stamp: 'Vendor Stamp',
    secondPartyStamp: 'Vendor Stamp',
    // The stamp maker uploads the completed/stamped Discom document under this
    // established backend type. Keep the type unchanged so existing files work.
    pm_surya_ghar_stamp: 'Discom Submission (Stamped)',
    surya_gpa_stamp: 'PM Surya GPA Stamp',
    gpa_stamp: 'PM Surya GPA Stamp',
    meter_installation_photo: 'Meter Installation Photo',
    meter_photo: 'Meter Installation Photo',
    warranty_card: 'Warranty Card',
    insurance_status: 'Insurance Document',
    feasibilty_document: 'Feasibility Document',
    feasibility_document: 'Feasibility Document',
    subsidy_token_photo: 'Subsidy Token Photo',
    digital_certificate: 'Digital Certificate',
    discom_agreement: 'PM Surya Ghar Model Agreement'
};

// Which doc_type actually corresponds to a real boolean column on `admin`.
//
// Uploading a document auto-ticks the matching checklist flag. That write used
// to use the doc_type itself as the column name, so any doc_type that is only
// an alias (signature, stamp_pic, meter_photo...) or has no column at all
// (file_status - the column was dropped) made Postgres reject the whole
// update with "Could not find the '<x>' column of 'admin' in the schema
// cache". A doc_type absent from this map simply does not set a flag.
export const DOC_TYPE_FLAG_COLUMN = {
    application_acknowledgment: 'application_acknowledgment',
    vendor_feasibility:         'vendor_feasibility',
    site_feasibility:           'site_feasibility',
    adhaar_card_front:          'adhaar_card_front',
    adhaar_card_back:           'adhaar_card_back',
    pan_card:                   'pan_card',
    light_bill:                 'light_bill',
    index_2:                    'index_2',
    bank_details:               'bank_details',
    house_geo_tag_photo:        'house_geo_tag_photo',
    extra_docs:                 'extra_docs',
    geo_tag_image:              'geo_tag_image',
    sfdc_photo:                 'sfdc_photo',
    dcr_certificate:            'dcr_certificate',
    pcr_certificate:            'pcr_certificate',
    plant_commissioning_report: 'plant_commissioning_report',
    digital_certificate:        'digital_certificate',
    subsidy_token_photo:        'subsidy_token_photo',
    warranty_card:              'warranty_card',
    insurance_status:           'insurance_status',
    pm_surya_ghar_stamp:        'pm_surya_ghar_stamp',
    discom_agreement:           'discom_agreement',
    // Aliases -> the one real column they belong to
    signature_pic:              'signature_pic',
    signature:                  'signature_pic',
    firstPartySignature:        'signature_pic',
    customer_signature:         'signature_pic',
    stamp:                      'stamp',
    stamp_pic:                  'stamp',
    vendor_stamp:               'stamp',
    secondPartyStamp:           'stamp',
    meter_installation_photo:   'meter_installation_photo',
    meter_photo:                'meter_installation_photo',
    // The real column carries the original spelling of "feasibilty"
    feasibilty_document:        'feasibilty_document',
    feasibility_document:       'feasibilty_document',
    // Intentionally unmapped: file_status, surya_gpa_stamp, gpa_stamp.
    // NOTE on file_status: a column of that name exists again, but it is TEXT,
    // not boolean. This map sets its target to `true` on upload, so mapping
    // file_status here would write a boolean into a text column and fail the
    // whole update. Leave it out.
};

// ════════════════════════════════════════════════════════════
// ACTIVITY LOG & ACTION COLORS
// ════════════════════════════════════════════════════════════
export const ACTION_COLORS = {
    create:   { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', dot: 'bg-emerald-500', label: 'Created' },
    update:   { bg: 'bg-blue-50',    text: 'text-blue-700',    border: 'border-blue-200',    dot: 'bg-blue-500',    label: 'Updated' },
    delete:   { bg: 'bg-rose-50',    text: 'text-rose-700',    border: 'border-rose-200',    dot: 'bg-rose-500',    label: 'Deleted' },
    recall:   { bg: 'bg-amber-50',   text: 'text-amber-700',   border: 'border-amber-200',   dot: 'bg-amber-500',   label: 'Recalled' },
    upload:   { bg: 'bg-purple-50',  text: 'text-purple-700',  border: 'border-purple-200',  dot: 'bg-purple-500',  label: 'Uploaded' },
    download: { bg: 'bg-indigo-50',  text: 'text-indigo-700',  border: 'border-indigo-200',  dot: 'bg-indigo-500',  label: 'Downloaded' },
    login:    { bg: 'bg-stone-50',   text: 'text-stone-700',   border: 'border-stone-200',   dot: 'bg-stone-500',   label: 'Logged In' },
};

// ════════════════════════════════════════════════════════════
// CHECKLIST FIELDS
// ════════════════════════════════════════════════════════════
export const REG_CHECKLIST_FIELDS = [
    { field: 'adhaar_card_front', label: 'Adhaar Card (Front)' },
    { field: 'adhaar_card_back', label: 'Adhaar Card (Back)' },
    { field: 'pan_card', label: 'PAN Card' },
    { field: 'index_2', label: 'Index-2' },
    { field: 'light_bill', label: 'Light Bill' },
    { field: 'bank_details', label: 'Bank Details' },
    { field: 'house_geo_tag_photo', label: 'House Photo with Geo Tag' },
    { field: 'extra_docs', label: 'Extra Docs' },
];

export const OPERATIONAL_CHECKLIST_FIELDS = [
    { field: 'digital_certificate', label: 'Digital Certificate' },
    { field: 'feasibilty_document', label: 'Feasibility Document' },
    { field: 'subsidy_token_photo', label: 'Subsidy Token Photo' },
    { field: 'meter_installation_photo', label: 'Meter Installation Photo' },
    { field: 'geo_tag_image', label: 'Geo Tag Image' },
    { field: 'dcr_certificate', label: 'DCR Certificate' },
    { field: 'signature_pic', label: 'Signature Pic' },
    { field: 'pm_surya_ghar_stamp', label: 'PM Surya Ghar Stamp' },
    { field: 'vendor_feasibility', label: 'Vendor Feasibility' },
    { field: 'site_feasibility', label: 'Site Feasibility' },
];

// Every real column on the `admin` table, verified against the live schema on
// 2026-08-29. Used by sanitizeAdminUpdate() to strip keys that are not real
// columns before a write.
//
// WHY: several save paths write { ...editData }, i.e. the whole customer row.
// PostgREST rejects the ENTIRE update with 42703 if even one key is not a
// column, so a single stale key made every save in the Dealer Portal fail
// ("Could not find the 'file_status' column of 'admin' in the schema cache").
//
// KEEP THIS IN SYNC. If you add a column to `admin`, add it here too, or
// writes to it are dropped (a console warning is logged when that happens).
export const ADMIN_COLUMNS = new Set([
    'ac_cable',
    'adhaar_card_back',
    'adhaar_card_front',
    'application_acknowledgment',
    'application_done_by',
    'bank_branch',
    'bank_details',
    'bank_name',
    'cash_details',
    'channel_partner',
    'completed_at',
    'consumer_no',
    'created_at',
    'customer_name',
    'dc_cable',
    'dcr_certificate',
    'deleted_at',
    'delivery_batch_id',
    'delivery_status',
    'digital_certificate',
    'discom_inspection',
    'discom_submission',
    'driver_name',
    'driver_phone_number',
    'email_address',
    'extra_docs',
    'feasibility_no',
    'feasibilty_document',
    'folder_no',
    'full_address',
    'follow_ups',
    'geo_tag_image',
    'geo_tag_status',
    'hold_procurement',
    'house_geo_tag_photo',
    'id',
    'index_2',
    'installation_date',
    'installation_note',
    'installation_status',
    'insurance_status',
    'internal_remarks',
    'inverter_make',
    'inverter_serial_no',
    'invoice_no',
    'invoice_value',
    'jansamarth_application_no',
    'light_bill',
    'loan_history',
    'loan_by',
    'loan_registration_date',
    'loan_tag',
    'material_delivery_date',
    'material_order_notes',
    'meter_installation',
    'meter_installation_photo',
    'module_brand',
    'module_wp',
    'no_of_modules',
    'pan_card',
    'pcr_certificate',
    'panel',
    'panel_serial_no',
    'payment_type',
    'plant_commissioning_report',
    'phone_number',
    'pincode',
    'pm_surya_ghar_stamp',
    'registration_by',
    'registration_date',
    'registration_no',
    'roof_shed',
    'sfdc_photo',
    // Free-text siblings of the sfdc_photo / warranty_card checkboxes, plus
    // file_status which has no checkbox at all. These MUST be listed here - a
    // column missing from ADMIN_COLUMNS is stripped by sanitizeAdminUpdate, so
    // the field would save "successfully" and write nothing.
    'sfdc_photo_text',
    'warranty_card_text',
    'file_status',
    'signature_pic',
    'site_feasibility',
    'stage',
    'stages_remarks',
    'stamp',
    'structure_front_leg_height',
    'structure_rear_leg_height',
    'sub_channel_partner',
    'sub_divisions',
    'district',
    'subsidy_history',
    'subsidy_tag',
    'subsidy_token_photo',
    'system_capacity_kwp',
    'updated_at',
    'vehicle_number',
    'vendor',
    'vendor_feasibility',
    'vendor_give_up_approved',
    'vendor_note',
    'vendor_paid_by',
    'vendor_paid_date',
    'vendor_payment_status',
    'vendor_quote',
    'villages',
    'warranty_card'
]);

// Numeric / integer columns on `admin`, verified against the live schema on
// 2026-08-30. An empty string sent to any of these is rejected by Postgres
// ("invalid input syntax for type numeric"), so callers must convert '' to null.
//
// The previous hand-written list was missing phone_number, folder_no,
// driver_phone_number and both structure leg heights - so simply CLEARING any
// of those fields made the whole save fail. It also listed three columns
// (loan_sanction_amount, loan_disbursed_amount, subsidy_amount) that do not exist.
export const ADMIN_NUMERIC_COLUMNS = [
    'ac_cable',
    'dc_cable',
    'driver_phone_number',
    'folder_no',
    'invoice_value',
    'module_wp',
    'no_of_modules',
    'phone_number',
    'structure_front_leg_height',
    'structure_rear_leg_height',
    'system_capacity_kwp',
    'vendor_quote',
];

export const DEFAULT_PAGE_SIZE = 50;

// Optimized Column Selectors for List Views (prevents downloading 67+ full columns)
// Verified against the live `admin` schema on 2026-08-29. Every name here must
// be a real column - PostgREST rejects the WHOLE query with 42703 otherwise,
// which is how these views once went completely empty. Six phantom columns
// (crn, remarks, vendor_status, location_link, google_docs, bank_name) were
// removed from this list.
// Also covers the fields handleMoveStage validates before letting a lead leave
// the Leads stage (villages, module_brand, sub_divisions) - narrowing the grid
// query without these would make that check see undefined and falsely block.
export const CUSTOMER_CARD_COLUMNS = 'id, customer_name, phone_number, email_address, consumer_no, folder_no, stage, channel_partner, sub_channel_partner, payment_type, loan_tag, subsidy_tag, installation_status, system_capacity_kwp, module_brand, module_wp, no_of_modules, villages, full_address, pincode, sub_divisions, district, registration_date, invoice_value, vendor_quote, created_at, updated_at, deleted_at, delivery_batch_id, delivery_status, stages_remarks, vendor, geo_tag_status';

// Vendor list cards and stage counters do not need the full admin record. The
// complete record is fetched only when a vendor opens one assignment.
export const VENDOR_LIST_COLUMNS = 'id, customer_name, phone_number, email_address, consumer_no, folder_no, stage, vendor, deleted_at, installation_status, geo_tag_status, villages, sub_divisions, district, system_capacity_kwp, module_brand, module_wp, no_of_modules, created_at, updated_at';

export const DELIVERY_PICKER_COLUMNS = 'id, customer_name, phone_number, consumer_no, folder_no, stage, channel_partner, sub_channel_partner, system_capacity_kwp, module_wp, no_of_modules, invoice_value, delivery_batch_id, delivery_status, material_delivery_date, driver_name, driver_phone_number, vehicle_number, vendor, created_at, updated_at, deleted_at';

// A tag value is "final" when it is the terminal state of its set. Reaching it
// locks the field for everyone except Admin. Driven by the isFinal flag on the
// tag definitions above, so changing which value locks is a one-word edit.
export const isFinalTagValue = (value, tags = []) => {
    const v = String(value ?? '').trim().toLowerCase();
    if (!v) return false;
    return tags.some(t => t.isFinal && String(t.id).trim().toLowerCase() === v);
};
